name: Save Ranking Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON 数据'
        required: true

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Save data.json
        run: |
          echo '${{ github.event.inputs.data }}' > data.json
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Update ranking data"
          git push
